version: '3'
services:
  db:
    container_name: ${DB_HOST}
    image: ${DB_IMAGE}
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "${DB_PORT}:5432"
    command: '-c shared_buffers=4096MB -c max_connections=800'
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
volumes:
  db-data:

networks:
  default:
    name: ${NETWORK_NAME}
    external: true
